version: "3.8"

services:
  mongo1:
    image: mongo
    container_name: mongo1
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30001"]
    volumes:
      - ./data/mongo-1:/data/db
    ports:
      - 30001:30001

  mongo2:
    image: mongo
    container_name: mongo2
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30002"]
    volumes:
      - ./data/mongo-2:/data/db
    ports:
      - 30002:30002

  mongo3:
    image: mongo
    container_name: mongo3
    command: ["--replSet", "my-replica-set", "--bind_ip_all", "--port", "30003"]
    volumes:
      - ./data/mongo-3:/data/db
    ports:
      - 30003:30003

  mongoinit:
    image: mongo
    # this container will exit after executing the command
    restart: "no"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: >
      mongosh --host mongo1:30001 --eval 
      '
      config = {
      "_id" : "my-replica-set",
      "members" : [
        {
          "_id" : 0,
          "host" : "mongo1:30001"
        },
        {
          "_id" : 1,
          "host" : "mongo2:30002"
        },
        {
          "_id" : 2,
          "host" : "mongo3:30003"
        }
      ]
      };
      rs.initiate(config);
      ' 