apiVersion: apps/v1
kind: Deployment
metadata:
  name: rgirodon-nodejs-helloword
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rgirodon-nodejs-helloword
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: rgirodon-nodejs-helloword  
    spec:     # pod spec                  
      containers: 
      - name: nodejs-helloword 
        image: rgirodon/nodejs_helloword # image we pushed
        imagePullPolicy: Never
        ports:
        - containerPort: 8080